Feature/#109 - Synchronizing game inputs
courselab/snaskii21 pull request #110
Opened 2021-11-25 18:57 UTC by MauricioGGCatellan

Fixes #109 .

This PR proposes the following change:
- Sleep between each received input, so that too fast inputs aren't allowed. The sleep command utilizes the game delay variable, therefore it is syncronized with frame changes. This way, gameplay experience isn't affected.

2021-11-25 19:28 UTC, Dauboau approved these changes
I could reproduce the bug and this pull request, in fact, prevents it from happening.

2021-11-25 19:44 UTC, Dauboau requested changes
Just one observation, I think AUTHORS is a file that has been added accidentally which may not be necessary.

2021-11-29 16:14 UTC, JulioEO commented on src/ttsnake.c
> +#define ENERGY_BLOCK '+'	 /* Character to draw the energy block. */
```suggestion
#define ENERGY_BLOCK     '+'	 /* Character to draw the energy block. */
```
Just maintaning consistency here.

2021-11-29 22:20 UTC, Dauboau approved these changes

2021-11-29 22:21 UTC, merged