Add fruit collectable in the game
courselab/snaskii21 pull request #186
Opened 2021-12-22 14:24 UTC by Tyago-Teoi

Fixes #166.

The game now have a new collectable
represented with the character '$'.

This collectable can give to the player
some additional points, but it doesn't increase
the player energy or the snake size.

2021-12-22 17:02 UTC, JulioEO requested changes
Just grammar and coding style fixes. The mechanic itself seems to be working fine.

2021-12-22 17:02 UTC, JulioEO commented on src/ttsnake.c
> +  /* Verifies if the fruit is in a pair position, 'cause the snake moves 2 pos horizontally */
```suggestion
  /* Verifies if the fruit is in an even position, because the snake moves 2 positions horizontally */
```

2021-12-22 17:02 UTC, JulioEO commented on src/ttsnake.c
> +/* Spawns an fruit_block on the map. */
```suggestion
/* Spawns a fruit_block on the map. */
```

2021-12-22 17:02 UTC, JulioEO commented on src/ttsnake.c
> +  scene[0][fruit_block.y][fruit_block.x] = FRUIT_BLOCK;
```suggestion
	scene[0][energy_block[0].y][energy_block[0].x] = ENERGY_BLOCK;

        scene[0][fruit_block.y][fruit_block.x] = FRUIT_BLOCK;
```

2021-12-22 17:02 UTC, JulioEO commented on src/ttsnake.c
>  		spawn_energy_block();
```suggestion
                grown_snake();
		spawn_energy_block();
```

2021-12-22 19:11 UTC, Tyago-Teoi reviewed
All done

2021-12-24 02:41 UTC, JulioEO approved these changes

2021-12-24 02:45 UTC, merged